### PR TITLE
Update to use ServiceException.

### PR DESCRIPTION
**Pull request by ajt001**
Use ServiceException.

### CODE REVIEW

**Comment by camerojo** [comment]
Hi Andrew! What a pleasant surprise! @ajt001 

Are you interested in contributing to the TC? You would be very welcome!

We could have a chat some time - together with TBB's CTO Sadat Malik.

**Comment by ajt001** [comment]
> Hi Andrew! What a pleasant surprise! @ajt001
> 
> Are you interested in contributing to the TC? You would be very welcome!
> 
> We could have a chat some time - together with TBB's CTO Sadat Malik.

Hi John,
I've had a look a couple of times at the code, but never went as far as doing everything to get it running. 
I still need a database and the AWS keys so maybe someone could share those :) 

If I could contribute then I'd love to. I might need a lot of hand-holding 🔥 . As you might expect I've never had enough time, but I have a little more now being unemployed!
It would be worth a discussion, as I think knowing the flows, architecture etc needs a little insight from the experts!

**Comment by camerojo** [comment]
Let's chat then after Easter. I am in East Melbourne. Could we catch up for a coffee some time?

**Comment by camerojo** [comment]
I can't find your personal email address. Let's line up a catch up on email. Can you drop me an email at john@cameronfoundation.org @ajt001

**Comment by sadatmalik** [comment]
Hi @ajt001 

Great seeing you here! Would love to have a catch up with you and John 😄 

We've a couple of other open issues around exception handling noted in our backlog. . . but I don't mean to jump the gun!

**Comment by ajt001** [comment]
> Hi @ajt001
> 
> Great seeing you here! Would love to have a catch up with you and John 😄
> 
> We've a couple of other open issues around exception handling noted in our backlog. . . but I don't mean to jump the gun!

Hi Sadat, 
I've been doing a small bit of looking through the code around how exceptions are done - I think there is some opportunities. Agree not to jump the gun :) 

Look forward to a catch up with yourself and John. I'm still planning out my schedule, I'll keep in touch.

**Pull request closed without merging**
