### PR TITLE
Change - Accordion panel title as requested

### LINKED ISSUE #709: Full Intake: Dependents - intake screen changes only
See: https://www.canva.com/design/DAFtz28cQHE/JZI_5copovFN8N1fE2lQYg/view

Implement intake screen only changes to Dependents from the relevant slides.

### PR DESCRIPTION
**Pull request by cazcam34**
ONLY the change to the panel (dependants to family members/dependants). The other changes to the dependants questions are removals which need more discussion.

### CODE REVIEW

**Review by camerojo — CHANGES_REQUESTED** [review]
Typo - Dependants

See https://www.easybib.com/guides/grammar-guides/vocabulary/confusing-words/dependant-vs-dependent/

**Comment by cazcam34** [comment]
I just followed the spelling from the intake doc provided. Looking into it also it seems dependent is following american english which is probably where they are coming from, what english whould we be going off? https://www.merriam-webster.com/grammar/spelling-variants-dependent-vs-dependant
Screen Shot 2024-03-12 at 8 13 30 pm

**Comment by camerojo** [comment]
I would change it. The article you quoted said you can use either in the US - but outside US there is a difference.

And in the article it says "To be safe, use 'dependant' as a noun ... and in Britain." It is being used as noun here.

**Comment by cazcam34** [comment]
Ready for a review again

**Review by camerojo — APPROVED** [review]

**Pull request merged**
