### PR TITLE
Added multi-select dropdown filter for UNHCR status

### LINKED ISSUE #926: Add UNHCR status search filter
Add a search criteria that allows selection on candidate's registration status. 

The Welcome Corps at Work program only allows candidates who are UNHCR registered. Filtering on this would make source's and destination's work faster.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1714399165391329?thread_ts=1714399165.391329&cid=C42S4AJ73)

### PR DESCRIPTION
**Pull request by samschlicht**
Screenshot 2024-05-01 at 1 12 49 PM

Screenshot 2024-05-01 at 1 12 32 PM

### CODE REVIEW

**Comment by samschlicht** [comment]
@cazcam34 if you could peruse this and check that it doesn't interfere in any way with your work in the same area, that'd be much appreciated!

From what I gathered on Tuesday, you've already done the work to make unhcr_status the authoritative field for this info, and I'm just exposing that to search and not touching any other functionality. But do let me know if you have any reservations. Except that, this is good to go.

**Review by cazcam34 — COMMENTED** [review]
Thanks @samschlicht this won't affect anything I've worked on. As you mentioned it's just focused on the search functionality, whereas I'm looking at the intake. Looks great!

**Comment by samschlicht** [comment]
Thanks, @cazcam34!

**Review by camerojo — APPROVED** [review]
Approved.

Great work - lots of little fiddly things to get right.

**Pull request merged**
