### PR TITLE
Flyway changes

### PR DESCRIPTION
**Pull request by jennyglassmyer**
Adjusts flyway migrations stopping build of the server

### CODE REVIEW

**Review by talentbeyondboundaries — COMMENTED** [review]
The only difference here is that a blank line has been removed.

We don't need to change V1_168

**Review by talentbeyondboundaries — COMMENTED** [review]
I don't think we want the status to be null. The proper change for this is when we add a user - particularly the default SystemAdmin user we need to set status.

I have updated SystemAdminConfiguration to set the status of the auto created SystemAdminUser, so I think we can leave status being defined as not null.

That is the proper fix - not to allow status to be null.

**Review by talentbeyondboundaries — COMMENTED** [review]
I have also removed all the automatically created users. 

They are not needed.

**Review by talentbeyondboundaries — COMMENTED** [review]
I can't remember why created_by needed to be null so I am leaving it as not null.
It owuld be better to fix any code that does not supply a created_by

**Review by talentbeyondboundaries — COMMENTED** [review]
Rather than comment these out, it is better to delete them.

We can always see previous values if we ever need to through version control.

**Comment by talentbeyondboundaries** [comment]
I have applied all these changes to the latest code. The code that you are working from is quite old.

So nothing for you to do.

**Review by talentbeyondboundaries — COMMENTED** [review]
Shoudl be able to V1_210 in - I don't see why it should fail.

And partner abbreviations should not be null.

**Comment by camerojo** [comment]
Closing this pull request. I have manually updated selected Flyway changes as indicated in above comments

**Pull request closed without merging**
