### PR TITLE
288 add missing fields + backend code for canada visa intake

### LINKED ISSUE #288: Add missing fields + backend code for Canada visa intake
_As staff filling out a visa intake, 
I would like to be able to save data from the intake,
So that I can store this useful information._

New fields to be added on the backend to Candidate Visa Job Object:
- [x]  workExp
- [x]  ageRequirement
- [x]  preferredPathways
- [x]  ineligiblePathways
- [x]  eligiblePathways
- [x]  occupationCategory
- [x]  occupationSubcategory

### PR DESCRIPTION
**Pull request by cazcam34**
Missing a flyway to add the new visa job check fields - waiting on if I need to wait for a staging merge with 272 flyway before I add 273.

### CODE REVIEW

**Comment by cazcam34** [comment]
Sorry for the large pull request - it ended up being more of a refactor branch and it took me a while to figure out the best way to do this.

**Review by camerojo — DISMISSED** [review]
This looks good to me @cazcam34 . The Flyway you were waiting for is in staging now - so you can merge with staging. 

When your PR is in staging, I will be able to get my PR out.

**Comment by cazcam34** [comment]
Thanks @camerojo I made the put in Kat's changes and so I've taken it out of draft and once reviewed I can merge into staging.

**Review by camerojo — APPROVED** [review]
Approved

Let me know when you have merged @cazcam34. Then I can get my Flyway in as well.

**Pull request merged**
