### PR TITLE
all live candidates nightly SF->TC sync

### LINKED ISSUE #402: Sync TC candidates to SF
As a TBB staff member
I would like to be able to access and analyse live-ish candidate data using Salesforce and Sopact reporting tools
To better understand and present information regarding our candidates

This was primarily instigated by the Sopact-TBB team's request for access to this data for the impact dashboard. There have also been other requests, such as from the comms team to populate their candidate mailing list and more efficiently produce the Talent Catalog snapshot.

John met with Sopact and tentatively settled on the most efficient and secure way of achieving this being to extend our SF API connection to include all live candidate records.

The Sopact team and other stakeholders will need to decide what data they need to gather on SF and as part of this issue we'll adapt the contact records accordingly. Then we can set up a nightly sync.

### PR DESCRIPTION
**Pull request by samschlicht**

### CODE REVIEW

**Comment by samschlicht** [comment]
@sadatmalik @camerojo 
Just noting that the failed check is the same as last time I had to amend the terraform build — Sadat surveyed it as harmless and we went ahead without issues!

**Review by camerojo — DISMISSED** [review]

**Comment by sadatmalik** [comment]
Here's the analysis from the previous time when we have encountered an issue with the Terraform plan action:

https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1694697103881089

The conclusion at that time was this could be safely ignored. The issue was that the Plan step was failing because it could not yet retrieve the terraform.tfvars file - which is what we would expect.

The issue this time is a different failure cause - it is the Init step that is failing, not the Plan step like before.

Needs further investigation before merging.

**Review by sadatmalik — CHANGES_REQUESTED** [review]
See my PR comment - need to check the failed Terraform action. It is failing on a different step than the previous time.

**Comment by samschlicht** [comment]
Thanks, @sadatmalik! The errors on the checks for my previous SF issue #169 were actually the same, as pictured:
Screenshot 2024-01-10 at 1 01 40 pm

Screenshot 2024-01-10 at 1 02 21 pm

I think the confusion may stem from your Slack post having addressed the errors that were causing the fail (Exit code 1), but not the deprecation warnings. Noting that I decided to fix those warnings anyway, moving forward as #557. 

There's a similar deprecation warning for tc-build so I've logged that as issue #558.

**Comment by samschlicht** [comment]
@sadatmalik I'm actually thinking we should do this TODO to avoid future confusion resulting from Terraform checks, so I've logged it as issue #559.

`      - name: Plan Terraform
        id: plan
        run: |
          terraform plan -no-color -input=false
        # TODO: terraform.tfvars should be copied from github secrets to the env.INFRA_PATH directory
        continue-on-error: true
        working-directory: ${{ env.INFRA_PATH }}`

**Comment by samschlicht** [comment]
@sadatmalik actually just realised I didn't fully address your comment — you may not remember last time we were up against this failed terraform check, we actually took a little run at it with John in the dev meeting. 

We appended the init statement like so: `terraform init -upgrade`, which got us past the init stage and onto plan, where it subsequently failed anyway. It's at that point that you did your investigation resulting in the Slack post. So, unless I'm missing something, we have the same error. I've made a note to discuss in our 1-1.

**Comment by sadatmalik** [comment]
Hey @samschlicht just noting that the error was indeed different. In the action summary you will see it terminate with exit code 1 in each case. This is what you have posted above. But it is a little misleading as the action itself is named Terraform plan, so it appears as if it's failed on the "plan" step in both cases. However you need to click into the action details to see where it actually failed:

Pre-Christmas - init step failing:
Screenshot 2024-01-12 at 09 17 42

Now - plan step failing:
Screenshot 2024-01-12 at 09 18 48

You are correct though that it is the `terraform init -upgrade` that was required at the init step failure - well done for remembering. I do recall now that we did this in a 1-1 when troubleshooting it the first time around. Worth documenting all this.

Now that it is failing at the plan step - it is - as before - safe to ignore. Therefore I'm removing the check PR status. Unfortunately it's picked up some merge conflicts; but it is good to go once they are resolved.

**Review by sadatmalik — DISMISSED** [review]

**Review by sadatmalik — APPROVED** [review]
Approved

**Pull request merged**
